//UN BUCLE FOR ES UN ITERADOR QUE NOS AYUDA A RAPIDAMENTE A REPETIR EL BUCLE, ACTUALIZANDOSE SEGUN LO QUE LE DIMOS EN SU EXPRESION INICIAL, CONDICION Y EXPRESION FINAL. COMO EN EL SIGUIENTE EJEMPLO:

var numero = 30;
for (var i = 0; i < numero ; i++) {
    console.log(i)
}

//SE SUELE USAR MUY SEGUIDO LA VOCAL i COMO ITERADOR (NO SIEMPRE)