//UN BUCLE WHILE, ES UN ITERADOR, SI SE CUMPLE LA CONDICION DENTRO DEL WHILE, SE VA A REPETIR HASTA QUE LA CONDICION YA NO PUEDA CUMPLIRSE, LA EXPRESION SIEMPRE SE VA A EVALUAR ANTES DE VOLVER A REPETIR EL CICLO

//POR EJEMPLO:

var x = 0;
var y = 100;

while (x < 10) {
    x++;
    y--;
}

console.log(x, y)